# handlers file for nomad
---

- name: restart nomad in Ubuntu
  become: true
  systemd:
    daemon_reload: true
    name: nomad
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_facts['os_family'] == "Ubuntu"


- name: restart nomad in Alpine
  ansible.builtin.service:
    name: nomad
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_facts['os_family'] == "Alpine"
