# handlers file for nomad
---
- name: restart nomad
  become: true
  systemd:
    daemon_reload: true
    name: nomad
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_facts['os_family'] == "Ubuntu"
