---
- hosts: all
  become: yes
  tasks:

  - name: Set a hostname
    ansible.builtin.hostname:
      name: monitoring

  - name: Set timezone to Europe/Kiev
    community.general.timezone:
      name: Europe/Kiev

  - name: Get stats of docker dir
    ansible.builtin.stat:
      path: /root/.docker
    register: dot_docker

  - name: Create dir .docker
    ansible.builtin.file:
      path: /root/.docker
      owner: root
      group: root
      state: directory
      mode: '0755'
    when: dot_docker.stat.exists == false

  - name: Deploy docker auth
    ansible.builtin.file:
      path: /root/.docker/config.json
      owner: root
      group: root
      mode: '0644'
      state: absent

  - name: Install Prometheus
    include_role:
      name: cloudalchemy.prometheus
    vars:
      prometheus_version: 2.25.0
      prometheus_web_listen_address: 0.0.0.0:9098
      prometheus_db_dir: /var/lib/prometheus
      prometheus_targets:
        node:
        - targets:
          - 192.168.50.3:9100

  - name: Install Grafana
    include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_address: 0.0.0.0
      grafana_port: 3000
      prometheus_web_listen_address: 127.0.0.1:9098
      grafana_security:
        { admin_user: admin, admin_password: "rfhnjxrf67" }
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: server
          url: 'http://{{ prometheus_web_listen_address }}'
          basicAuth: false
 #     grafana_dashboards:
 #       - dashboard_id: 111
 #         revision_id: 1
 #         datasource: prometheus