---
- hosts: all
  become: yes
  vars_files:
   - vars.yaml
  tasks:


  - name: Set a hostname
    ansible.builtin.hostname:
      name: monitoring

  - name: Set timezone to Europe/Kiev
    timezone:
      name: Europe/Kiev

  - name: Creates directory
    ansible.builtin.file:
      path: /data
      state: directory
      mode: '777'
      recurse: yes

  - name: Install Prometheus
    include_role:
      name: cloudalchemy.prometheus
    vars:
      prometheus_version: 2.25.0
      prometheus_web_listen_address: "{{ prometheus_ip }}"
      prometheus_db_dir: /data
      prometheus_targets:
        node:
        - targets:
          - 192.168.50.2:9100

  - name: Install Node Exporter
    include_role:
      name: cloudalchemy.node-exporter

  - name: Grafana
    include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "{{grafana_password}}"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: 'http://{{ prometheus_ip }}'
          basicAuth: false

  - name: Change Grafana User
    community.grafana.grafana_user:
      url: "http://{{ node_ip }}:3000"
      url_username: admin
      url_password: "{{ grafana_password }}"
      name: "Bruce Wayne"
      email: batman@gotham.city
      login: batman
      password: "{{ grafana_password_batman }}"
      is_admin: true
      state: present
