---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ubuntu-18.04
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    pre_build_image: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: docker-alpine
    image: dockage/alpine-openrc
    pre_build_image: false
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    dockerfile: Dockerfile-alpine
    command: "/bin/sh -c 'trap : TERM INT; sleep 9999999999d & wait'"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro   
provisioner:
  name: ansible
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: testinfra
