---
- hosts: all
  become: true

  tasks:

  - name: Install Grafa
    include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "{{ grafana_password }}"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: 'http://{{ node_ip }}:9090'
          basicAuth: false
      grafana_dashboards:
        - dashboard_id: 11074
          revision_id: 1
          datasource: prometheus

  - name: Import grafana dashboards-1
    uri:
      url: "http://{{ node_ip }}:3000/api/dashboards/import"
      user: admin
      password: "{{ grafana_password }}"
      force_basic_auth: true
      method: POST
      body_format: json
      src: d111.json
