---
- hosts: all
  become: true

  tasks:

  - name: Install Grafa
    include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "{{ grafana_password }}"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: 'http://{{ node_ip }}:9090'
          basicAuth: false
