---
- name: Copy the nomad systemd service file
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify: restart nomad in Ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Copy the nomad openrc script
  template:
    src: nomad
    dest: /etc/init.d/nomad
    owner: root
    group: root
    mode: 0755
  notify: restart nomad in Alpine
  when: ansible_facts['distribution'] == "Alpine"


- name: Copy the nomad config file Ubuntu
  template:
    src: base.hcl.j2
    dest: "{{ nomad_conf_dir }}/{{ nomad_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nomad in Ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Copy the nomad config file Alpine
  template:
    src: base.hcl.j2
    dest: "{{ nomad_conf_dir }}/{{ nomad_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nomad in Alpine
  when: ansible_facts['distribution'] == "Alpine"
