---
- name: Copy the nomad systemd service file
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify: restart nomad
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Copy the nomad openrc script
  template:
    src: nomad
    dest: /etc/etc/init.d/nomad
    owner: root
    group: root
    mode: 0644
  notify: restart nomad
  when: ansible_facts['os_family'] == "Alpine"


- name: Copy the nomad config file
  template:
    src: base.hcl.j2
    dest: "{{ nomad_conf_dir }}/{{ nomad_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nomad
